services:
  shinobi:
    image: shinobi:latest
    container_name: shinobi-container
    volumes:
      - /var/lib/shinobi:/var/lib/shinobi
      - /var/log/shinobi:/root/.pm2/logs
      - /etc/shinobi/super.json:/opt/shinobi/super.json
    devices:
      - /dev/dri:/dev/dri
    environment:
      - LIBVA_DRIVER_NAME=i965
    ports:
      - "8080:8080"
      - "1337:1337"
    networks:
      - mysql

networks:
  mysql:
    name: mysql_default
    external: true
